@extends('layouts.app')

@section('content')

    <head>
        <link rel="stylesheet" href="{{ asset('css/form.css') }}">
        <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet" />
    </head>

    <body>
        <?php $regData = \App\CoreFunction\Helper::regData(); ?>
        <div class="container">
            <div class="row d-flex justify-content-center text-center">
                <h2 class="my-3">ใบคำขอดำเนินการด้านเอกสาร (DAR)</h2>

                <div class="card p-4">
                    <div class="tab-content" id="pills-tabContent">
                        @if ($errors->any())
                            <div class="alert alert-danger" role="alert">
                                {{ $errors->first() }}
                            </div>
                        @endif
                        <form id="darForm" action="{{ route('store-dar-form') }}" method="post" enctype="multipart/form-data">
                            @csrf

                            <!-- Form fields remain the same -->
                            <div class="row g-3 mb-3 d-flex justify-content-center">
                                <div class="col-auto">
                                    <label for="bnum" class="col-form-label"><span class="text-danger">*</span>เลขที่หนังสือ</label>
                                </div>
                                <div class="col-8">
                                    <input type="text" name="bnum" id="bnum" value="DAR-ID-0{{ $len }}/{{ date('Y') + 543 }}" class="form-control" readonly required>
                                </div>
                            </div>

                            <div class="row g-3 mb-3 d-flex justify-content-center">
                                <div class="col-auto">
                                    <label for="req_for" class="col-form-label"><span class="text-danger">*</span>ขอเพื่อ</label>
                                </div>
                                <div class="col-8">
                                    <input type="text" name="req_for" id="req_for" value="แก้ไขเอกสาร" class="form-control" readonly required>
                                </div>
                            </div>

                            <div class="row g-3 mb-3 d-flex justify-content-center">
                                <div class="col-auto">
                                    <label for="doc_owner" class="col-form-label"><span class="text-danger">*</span>ผู้ถือครอง</label>
                                </div>
                                <div class="col-8">
                                    <input type="text" name="doc_owner" id="doc_owner" class="form-control bg-white" value="{{ optional(Auth::user()->getDpm)->prefix }}" required>
                                </div>
                            </div>

                            <div class="row g-3 mb-3 d-flex justify-content-center">
                                <div class="col-auto">
                                    <label for="req_by" class="col-form-label"><span class="text-danger">*</span>ผู้ขอ</label>
                                </div>
                                <div class="col-8">
                                    <input type="text" name="req_by" id="req_by" class="form-control bg-white" value="{{ Auth::user()->name }}" required>
                                </div>
                            </div>

                            <div class="row g-3 mb-3 d-flex justify-content-center">
                                <div class="col-auto">
                                    <label for="req_date" class="col-form-label"><span class="text-danger">*</span>วันที่ขอ</label>
                                </div>
                                <div class="col-8">
                                    <input type="date" name="req_date" id="req_date" class="form-control bg-white" value="{{ date('Y-m-d') }}" required>
                                </div>
                            </div>

                            <div class="row g-3 mb-3 d-flex justify-content-center">
                                <div class="col-auto">
                                    <label for="docTypesContainer" class="col-form-label">ประเภทเอกสาร</label>
                                </div>
                                <div class="col-8">
                                    <div id="docTypesContainer" class="d-flex ms-4 pt-2">
                                        <div class="row">
                                            <div class="d-flex ms-4">
                                                <div class="row" id="checkboxesRow">
                                                    <!-- Checkboxes will be generated by jQuery -->
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row g-3 mb-3 d-flex justify-content-center">
                                <div class="col-auto">
                                    <label for="docTargetContainer" class="col-form-label">เอกสารที่ดำเนินการ</label>
                                </div>
                                <div class="col-8">
                                    <div id="docTargetContainer" class="d-flex ms-4 pt-2">
                                        <select class="js-example-basic-single w-100" id="selectDocs" name="doc_target[]" multiple="multiple">
                                            {{-- <option value="AL">Alabama</option>
                                            <option value="WY">Wyoming</option> --}}
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="d-flex justify-content-center">
                                    <button id="cancelBtn" type="button" class="btn btn-danger ms-2">ยกเลิก</button>
                                    <button type="submit" class="btn btn-success ms-2">บันทึก</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <script src="https://fastly.jsdelivr.net/npm/sweetalert2@11"></script>
        <script type="text/javascript" src="https://fastly.jsdelivr.net/jquery/latest/jquery.min.js"></script>
        <script type="text/javascript" src="https://fastly.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

        <script>
            $(document).ready(function() {
                $('.js-example-basic-single').select2();
            });

            $(document).ready(function() {
                const docTypes = [
                    { id: 'WI', label: 'WI' },
                    { id: 'SOP', label: 'SOP' },
                    { id: 'POL', label: 'นโยบาย' },
                    { id: 'PRO', label: 'โครงการ' },
                    { id: 'MOU', label: 'MOU' },
                    { id: 'ANNO', label: 'ประกาศ' },
                    { id: 'checklist', label: 'CheckList' },
                    { id: 'course', label: 'Course' },
                    { id: 'media', label: 'Media' },
                    { id: 'COST', label: 'ต้นทุนงาน' },
                    { id: 'JD', label: 'JD' }
                ];

                // Generate checkboxes
                docTypes.forEach(type => {
                    const checkbox = `
                        <div class="form-check mx-3 col-lg-3 col-md-6">
                            <input class="form-check-input doc-type-checkbox" type="checkbox" value="${type.id}" name="doc_types[]" id="${type.id}">
                            <label class="form-check-label" for="${type.id}">
                                ${type.label}
                            </label>
                        </div>
                    `;
                    $('#checkboxesRow').append(checkbox);
                });

                // Cancel button
                $('#cancelBtn').on('click', function() {
                    Swal.fire({
                        title: 'ยกเลิกการบันทึกข้อมูล?',
                        text: "ข้อมูลของคุณจะถูกลบ!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'ตกลง!',
                        cancelButtonText: 'ย้อนกลับ'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            window.location.href = '{{ route('home') }}';
                        }
                    });
                });

                function getCheckedDocTypes() {
                    return $('input[name="doc_types[]"]:checked').map(function() {
                        return $(this).val();
                    }).get();
                }

                $('.doc-type-checkbox').on('click', function() {
                    const selectd_doc_types = getCheckedDocTypes();

                    // Send selected doc types to server and fetch matching documents
                    fetch('/form/get-from-type', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRF-TOKEN': '{{ csrf_token() }}'
                        },
                        body: JSON.stringify({ types: selectd_doc_types })
                    })
                    .then(response => {
                        if (!response.ok) throw new Error('Network response was not ok');
                        return response.json();
                    })
                    .then(payload => {
                        const docs = payload.data || payload; // handle server shape
                        const $select = $('#selectDocs');
                        $select.empty(); // clear existing options

                        docs.forEach(doc => {
                            const val = `${doc.type}-${doc.id}`;
                            const text = `${doc.book_num} :: ${doc.title}`;
                            const newOption = new Option(text, val, false, false);
                            $select.append(newOption);
                        });

                        // refresh select2 UI
                        $select.trigger('change');
                        // optionally auto-select first item:
                        // if (docs.length) $select.val(`${docs[0].type}-${docs[0].id}`).trigger('change');
                    })
                    .catch(error => {
                        console.error('Fetch error:', error);
                    });
                });

                // Form submission
                // $('#darForm').on('submit', function(e) {
                //     const selectedTypes = $('input[name="doc_types[]"]:checked').map(function() {
                //         return $(this).val();
                //     }).get();

                //     console.log('Selected doc types:', selectedTypes);
                //     // Form will submit normally
                // });
            });
        </script>
    </body>
@endsection
